---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
